# Generated by Django 5.0.3 on 2024-05-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_alter_consumer_id_alter_contact_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("dob", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
