# Generated by Django 5.0.3 on 2024-05-06 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0017_alter_alarm_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alarm",
            name="date",
        ),
        migrations.RemoveField(
            model_name="alarm",
            name="time",
        ),
    ]
